local Utils = {}

Utils.Assets = require(script:WaitForChild("Assets"))
Utils.Beam = require(script:WaitForChild("Beam"))
Utils.Cloner = require(script:WaitForChild("Cloner"))
Utils.Collection = require(script:WaitForChild("Collection"))
Utils.Color = require(script:WaitForChild("Color"))
Utils.Connections = require(script:WaitForChild("Connections"))
Utils.Debris = require(script:WaitForChild("Debris"))
Utils.Humanoid = require(script:WaitForChild("Humanoid"))
Utils.Instance = require(script:WaitForChild("InstanceUtil"))
Utils.Math = require(script:WaitForChild("Math"))
Utils.Model = require(script:WaitForChild("Model"))
Utils.Number = require(script:WaitForChild("Number"))
Utils.NumberRange = require(script:WaitForChild("NumberRange"))
Utils.NumberSequence = require(script:WaitForChild("NumberSequence"))
Utils.Player = require(script:WaitForChild("Player"))
Utils.Raycaster = require(script:WaitForChild("Raycaster"))
Utils.Screen = require(script:WaitForChild("Screen"))
Utils.Server = require(script:WaitForChild("Server"))
Utils.Signals = require(script:WaitForChild("Signals"))
Utils.Sound = require(script:WaitForChild("Sound"))
Utils.Spatial = require(script:WaitForChild("Spatial"))
Utils.Table = require(script:WaitForChild("Table"))
Utils.Teleport = require(script:WaitForChild("Teleport"))
Utils.TextAnimator = require(script:WaitForChild("TextAnimator"))
Utils.Time = require(script:WaitForChild("Time"))
Utils.Tween = require(script:WaitForChild("Tween"))
Utils.Weld = require(script:WaitForChild("Weld"))

return Utils
